# Generated by Django 4.2.18 on 2025-03-19 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_key', models.CharField(max_length=20)),
                ('total_distance', models.CharField(max_length=20)),
                ('total_pace', models.CharField(max_length=20)),
                ('average_pace', models.CharField(max_length=20)),
                ('average_heart_rate', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_data', to='runapp.runner')),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_number', models.CharField(max_length=10)),
                ('distance', models.CharField(max_length=20)),
                ('pace', models.CharField(max_length=20)),
                ('heart_rate', models.CharField(max_length=10)),
                ('history_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='runapp.historydata')),
            ],
        ),
    ]
