# Generated by Django 4.2.18 on 2025-03-20 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('runapp', '0002_historydata_segment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runner',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='runner', to=settings.AUTH_USER_MODEL),
        ),
    ]
