# Generated by Django 4.2.18 on 2025-03-20 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runapp', '0003_alter_runner_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='segment',
            old_name='heart_rate',
            new_name='heartRate',
        ),
        migrations.RenameField(
            model_name='segment',
            old_name='segment_number',
            new_name='segmentNumber',
        ),
    ]
