# Generated by Django 4.2.18 on 2025-03-21 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runapp', '0005_rename_average_heart_rate_historydata_averageheartrate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historydata',
            name='date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
